In [1]:
import pandas as pd
print("pandas is working")

pandas is working

In [2]:
import pandas as pd

df = pd.read_csv("raw_data.csv")
df.head()

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,2024-04-08,True
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,261.0,Digital Wallet,Online,2023-07-23,True
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2.0,43.0,Credit Card,Online,2022-10-05,False
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9.0,247.5,Credit Card,Online,2022-05-07,NaN
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7.0,87.5,Digital Wallet,Online,2022-10-02,False

In [3]:
df.shape

(12575, 11)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12575 entries, 0 to 12574
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    12575 non-null  str
 1   Customer ID       12575 non-null  str
 2   Category          12575 non-null  str
 3   Item              11362 non-null  str
 4   Price Per Unit    11966 non-null  float64
 5   Quantity          11971 non-null  float64
 6   Total Spent       11971 non-null  float64
 7   Payment Method    12575 non-null  str
 8   Location          12575 non-null  str
 9   Transaction Date  12575 non-null  str
 10  Discount Applied  8376 non-null   object
dtypes: float64(3), object(1), str(7)
memory usage: 1.9+ MB

In [5]:
df.isnull().sum()

Transaction ID         0
Customer ID            0
Category               0
Item                1213
Price Per Unit       609
Quantity             604
Total Spent          604
Payment Method         0
Location               0
Transaction Date       0
Discount Applied    4199
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df[['Price Per Unit', 'Quantity', 'Total Spent']].isnull().sum()

Price Per Unit    609
Quantity          604
Total Spent       604
dtype: int64

In [9]:
df[df[['Price Per Unit','Quantity','Total Spent']].isnull().any(axis=1)][['Price Per Unit','Quantity','Total Spent']].head(10)

    Price Per Unit  Quantity  Total Spent
5              NaN      10.0        200.0
7             33.5       NaN          NaN
11             NaN       8.0         52.0
15            24.5       NaN          NaN
17             NaN      10.0        275.0
19            35.0       NaN          NaN
21             NaN       3.0        105.0
25            39.5       NaN          NaN
32             NaN       8.0        196.0
34            23.0       NaN          NaN

In [10]:
df['Discount Applied'].unique()

array([True, False, nan], dtype=object)

In [11]:
# Rows missing Price: do they always have Quantity AND Total present?
missing_price = df[df['Price Per Unit'].isnull()]
missing_price[['Quantity', 'Total Spent']].isnull().sum()

Quantity       0
Total Spent    0
dtype: int64

In [12]:
# Rows missing Quantity: do they always have Total also missing?
missing_qty = df[df['Quantity'].isnull()]
missing_qty[['Price Per Unit', 'Total Spent']].isnull().sum()

Price Per Unit      0
Total Spent       604
dtype: int64

In [13]:
df['Price Per Unit'] = df['Price Per Unit'].fillna(df['Total Spent'] / df['Quantity'])

In [14]:
df['Price Per Unit'].isnull().sum()

np.int64(0)

In [15]:
df = df.dropna(subset=['Quantity', 'Total Spent'])
df.shape

(11971, 11)

In [16]:
df['Item'] = df['Item'].fillna('Unknown')

In [17]:
df['Discount Applied'] = df['Discount Applied'].fillna(False)

In [18]:
df['Transaction Date'] = pd.to_datetime(df['Transaction Date'])
df.info()

<class 'pandas.DataFrame'>
Index: 11971 entries, 0 to 12574
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    11971 non-null  str
 1   Customer ID       11971 non-null  str
 2   Category          11971 non-null  str
 3   Item              11971 non-null  str
 4   Price Per Unit    11971 non-null  float64
 5   Quantity          11971 non-null  float64
 6   Total Spent       11971 non-null  float64
 7   Payment Method    11971 non-null  str
 8   Location          11971 non-null  str
 9   Transaction Date  11971 non-null  datetime64[us]
 10  Discount Applied  11971 non-null  object
dtypes: datetime64[us](1), float64(3), object(1), str(6)
memory usage: 1.8+ MB

In [19]:
df['Discount Applied'] = df['Discount Applied'].astype(bool)
df.dtypes

Transaction ID                 str
Customer ID                    str
Category                       str
Item                           str
Price Per Unit             float64
Quantity                   float64
Total Spent                float64
Payment Method                 str
Location                       str
Transaction Date    datetime64[us]
Discount Applied              bool
dtype: object

In [20]:
df = df.reset_index(drop=True)
df.to_csv('cleaned_data.csv', index=False)